apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: demo:latest
          imagePullPolicy: Never
          resources:
            requests:
              memory: "256M"
              cpu: "0.25"
            limits:
              memory: "1024M"
              cpu: "0.5"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: management
              containerPort: 8558
              protocol: TCP
            - name: remoting
              containerPort: 2552
              protocol: TCP
          env:
            - name: JAVA_OPTS
              value: "-Xss8m -Xms256m -Xmx640m"
            - name: CONF_FILE_NAME
              value: "application-kube.conf"
          volumeMounts:
            - name: varlog
              mountPath: /var/log
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /alive
              port: management
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /ready
              port: management
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 15
      volumes:
        - name: varlog
          hostPath:
            path: /var/log