apiVersion: v1
kind: Service
metadata:
  name: demo-external
  labels:
    app: demo
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: demo
  type: LoadBalancer

