apiVersion: v1
kind: Service
metadata:
  name: sample-app #this should be the same as the Actor System Name (also the Akka Cluster Name)
  labels:
    app: demo
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - name: management
      port: 8558
      protocol: TCP
      targetPort: 8558
    - name: remoting
      port: 2552
      protocol: TCP
      targetPort: 2552
  selector:
    app: demo
  clusterIP: None
  publishNotReadyAddresses: true